### ISSUE TITLE
create installable zip

### ISSUE THREAD

**Issue by wdehoog** [ubports/rootstock-ng#6]
Currently the rootstock script does all kinds of stuff on the phone using adb. 
Instead of on the phone it could also prepare the filesystem on a pc so that it can be flashed using a zip. 
This allows people to try ubports before surrendering their precious phones to the installer.

**Comment by UniversalSuperBox** [comment]
Rootstock-touch-install should only be used to install UBports during development. After that, images should be packaged for system-image. This requires the UBports recovery or another recovery with system-image support.

Flashable zips don't exactly meet the goals of system-image and would wipe the phone anyway.

Does that make sense, or do you see another use case for this?

**Comment by wdehoog** [comment]
I needed it since my recovery does not give adb access. When in recovery adb lists the device as 'unauthorized' so no adb shell for me, so no installer script. 
In all honesty I just wanted to see how ubports worked not change my phone into ubports only. It could be a nice way for people to 'test' it.

**Comment by UniversalSuperBox** [comment]
This tool really isn't to "See how UBports works" or installing on any regular phone. It is meant for developers who are porting Halium and Ubuntu Touch to their device. The system.img that it uses must be provided from a Halium build tree following the documentation at https://docs.halium.org

I'm going to close this as a Won't Fix, out of scope.

(Also, if you're unauthorized in adb, try to use `sudo` with the adb command. Ensure that you've enabled developer mode and allowed your computer adb access while in the Android system)

**Comment by wdehoog** [comment]
Ok. The thing is I am a developer and I wanted to see how UBPorts works. As a matter of fact I did. See https://forums.ubports.com/topic/669/is-it-possible-to-flash-ubuntu-touch-without-an-installer/19.

I still think it would be a nice additional way to 'show off' how great your project is.
